name: On push build and push to gh-pages

on:
    push:
        branches: [master]

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v3.8.2

            - run: npm install
            - run: npm run build:verify

    build:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        needs: verify
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v3.8.2

            - run: npm install
            - run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3.5.10
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
